spring.application.name=glossary-service

#server configs
server.servlet.context-path=/glossary
server.port=8081
server.error.include-message=always


app.nombre=Aikido Glossary Api
app.lenguaje=ES
app.pais=Uruguay
app.author=Jessica Valiente

#Conexion a Base de datos
spring.datasource.platform=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/glossary
spring.datasource.username=postgres
spring.datasource.password=1234

# Specify explicitly the dialect (here for PostgreSQL, adapt for your database)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Disable Hibernate usage of JDBC metadata
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=false

# Database initialization should typically be performed outside of Spring lifecycle
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ejecutar contenedor docker
#docker run --name aikidoDB -p 5432:5432 -e POSTGRES_PASSWORD=1234 -e POSTGRES_DB=glossary -d postgres

